### ISSUE TITLE
Create a reusable page layout with header, sidebars, and footer

### ISSUE THREAD

**Issue by jackbemi** [EMI-Advisors/C4BH#26]
Each page should have a consistent layout. 
- [x] Design a page layout component which can contain the page components
- [x] Add a header, sidebars, and footer to the layout: design done, pulled into amplify, issues integrating into react
- [x] Design reactive resizing components 

https://matthewjamestaylor.com/holy-grail-layout (1)

**Comment by NotAnotherDoorNob** [comment]
The design of this is complete and can be found here: [](https://www.figma.com/file/mOtMkkvxbiiyPrcW0exjdG/C4BH-AWS-Amplify-UI-Kit?type=design&node-id=4901%3A3837&mode=design&t=Jsk205dBiWbBlOvl-1)

Please reach out to review before we start building
