### ISSUE TITLE
Side Nav Interactions (links & collapse)

### ISSUE THREAD

**Issue by jackbemi** [EMI-Advisors/C4BH#27]
Here is the figma file, it contains both the open and closed states: [https://www.figma.com/design/mOtMkkvxbiiyPrcW0exjdG/C4BH-AWS-Amplify-UI-Kit?node-id=4899%3A2895&t=FEAAWgkKJnlN9VQE-1](https://www.figma.com/design/mOtMkkvxbiiyPrcW0exjdG/C4BH-AWS-Amplify-UI-Kit?node-id=4899%3A2895&t=FEAAWgkKJnlN9VQE-1)

A static/non-interactice prototype of the new header, sidenav, and footer can be found in the [layout-testing](https://github.com/EMI-Advisors/C4BH/tree/layout-testing) branch.

- [ ] Add functional links to the side nav
- [ ] Give the links a selected state (home is selected in the figma example)
- [ ] Add show/hide button to show only icons - there may be a way to easily add onClick UI modifications in amplify studio [https://docs.amplify.aws/gen1/react/build-ui/uibuilder/eventhandling/](https://docs.amplify.aws/gen1/react/build-ui/uibuilder/eventhandling/)

**Comment by NotAnotherDoorNob** [comment]
This will likely need to be re-scoped, per #26 navigation will be located in the sidebar
