### ISSUE TITLE
Automate DxF Participant registry ingest

### ISSUE THREAD

**Issue by jackbemi** [EMI-Advisors/C4BH#32]
Write a schedulable task: probaably a cron job to curl the excel sheet url
Write a script to upload the data into dynamoDB
Add the columns from the DxF Participant excel sheet into the dynamoDB table & amplify data model

**Comment by NoahWGeorge** [comment]
finished automating the initial data ingest with connecting athena, quicksight, and dynamoDB. Need to attach second excel file (join with existing).
