### ISSUE TITLE
Add content to the homepage

### ISSUE THREAD

**Issue by jackbemi** [EMI-Advisors/C4BH#77]
- [x] homepage layout with placeholder content in figma
- [x] homepage layout in code
- [x] write out homepage content (collaborate with Kris on this)
- [ ] add written content to figma and code

Hompage figma layout with placeholder content can be found [here](https://www.figma.com/design/NiXuVn5Q4KpuczATW79Uhm/Home-page?node-id=40%3A526&t=HfecpaD8BMcndozz-1)

A version of the layout with placeholder content can be found in [layout-testing](https://github.com/EMI-Advisors/C4BH/tree/layout-testing)

**Comment by NotAnotherDoorNob** [comment]
@jackbemi I'm going to schedule a meeting with Kris to define the page content. I was also able to easily add the new landing page layout with the figma/amplify generated code in the layout-testing branch. This may be something I can handle
