### ISSUE TITLE
Modify Athena datasources

### ISSUE THREAD

**Issue by jackbemi** [EMI-Advisors/C4BH#80]
- [x] change sources from excel to dynamo
- [x] figure out why Athena isn't pulling in some columns? (glue fix)
- [x] table is blank except for zipcode cleaned col
- [x] get Athena to populate the columns correctly

dynamoDB & athena -> creates schema
dynamo nulls -> athena can't pull
AWS glue pulls dynamo table and schema even with nulls -> athena gets correct schema
AWS glue adds cloumnMapping property to Dynamo Table -> Athena can read column names

**Comment by jackbemi** [comment]
Issue could be related to data types
schema is wrong?
only one zip code column shows up

**Comment by pbaffes1** [comment]
Use AWS glue to map schema to Dynamo DB table and under table properties ensure to use columnMapping and define schema column names with only lower case letters.
